name: Code Coveralls

on:
    pull_request:
      branches:
        - master
jobs:
    build:
        runs-on:  ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Intall Node.js
          uses: actions/setup-nodev@v1
          with:
            node-version: 12.x

        - name: Install dependencies
          run: yarn
            
        - name: Test
          run: yarn test
        env:
            CI: true
