name: Code Coveralls

on:
    pull_request:
      branches:
        - master
jobs:
    build:
        runs-on:  ubuntu-latest
        if: github.event.pull_request.draft == false
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Intall Node.js
          uses: actions/setup-node@v2-beta
          with:
            node-version: 12.x

        - name: Install dependencies
          run: yarn
            
        - name: Test
          run: yarn test
        
        - uses: actions/checkout@master
        - uses: codecov/codecov-action@v1
          with:
              token: ${{ secrets.CODECOV_TOKEN }}
          
        env:
            CI: true
            CODECOV_TOKEN: "6d488a67-462d-4707-9c5d-0df67352b9e4"

